[tool.black]
line-length = 125
target-version = ["py39"]
include = '\.pyi?$'
extend-exclude = '''
^/env/
^/venv/
^/.venv/
^/build/
^/dist/
^/.git/
^/.pytest_cache/
^/__pycache__/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 125
skip = [
    ".git",
    ".pytest_cache",
    "__pycache__",
    "build",
    "dist",
    "env",
    "venv",
    ".venv"
]

[tool.mypy]
exclude = "env/.*|setup\\.py"
files = "src/"
check_untyped_defs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = false
warn_return_any = true
warn_unreachable = true

["tool.mypy-pygame.*"]
ignore_missing_imports = true

["tool.mypy-pytest.*"]
ignore_missing_imports = true
