from typing import List

import pytest

from src.config.language.language import Language


@pytest.fixture
def language() -> Language:
    """Fixture to create a Language instance for testing."""
    return Language()


def test_language_initialization(language: Language) -> None:
    """Test if the language system initializes correctly."""
    assert isinstance(language, Language)
    assert language.current_language in Language.SUPPORTED_LANGUAGES
    assert isinstance(language.translations, dict)
    for lang in Language.SUPPORTED_LANGUAGES:
        assert lang in language.translations


def test_get_text_english(language: Language) -> None:
    """Test getting English translations."""
    language.current_language = "en"
    assert language.get_text("game_controls") == "Game Controls"
    assert language.get_text("move_left_right") == "Move left/right"
    assert language.get_text("shoot") == "Shoot"
    assert language.get_text("pause_game") == "Pause game"
    assert language.get_text("quit_game") == "Quit game"
    assert language.get_text("press_space") == "Press SPACE to continue"
    assert language.get_text("play") == "Play"
    assert language.get_text("score") == "Score"
    assert language.get_text("high_score") == "High Score"
    assert language.get_text("level") == "Level"
    assert language.get_text("ships") == "Ships"
    assert language.get_text("game_over") == "Game Over"
    assert language.get_text("press_p") == "Press 'P' to resume"
    assert language.get_text("press_q") == "Press 'Q' to quit"
    assert language.get_text("toggle_music") == "Music on/off"
    assert language.get_text("toggle_sound") == "Sound on/off"
    assert language.get_text("paused_game") == "Paused Game"


def test_get_text_spanish(language: Language) -> None:
    """Test getting Spanish translations."""
    language.current_language = "es"
    assert language.get_text("game_controls") == "Controles del Juego"
    assert language.get_text("move_left_right") == "Mover izquierda/derecha"
    assert language.get_text("shoot") == "Disparar"
    assert language.get_text("pause_game") == "Pausar juego"
    assert language.get_text("quit_game") == "Salir del juego"
    assert language.get_text("press_space") == "Presiona ESPACIO para continuar"
    assert language.get_text("play") == "Jugar"
    assert language.get_text("score") == "Puntuación"
    assert language.get_text("high_score") == "Puntuación Máxima"
    assert language.get_text("level") == "Nivel"
    assert language.get_text("ships") == "Naves"
    assert language.get_text("game_over") == "Juego Terminado"
    assert language.get_text("press_p") == "Presiona 'P' para reanudar"
    assert language.get_text("press_q") == "Presiona 'Q' para salir"
    assert language.get_text("toggle_music") == "Música encendida/apagada"
    assert language.get_text("toggle_sound") == "Sonido encendido/apagado"
    assert language.get_text("paused_game") == "Juego en Pausa"


def test_get_text_french(language: Language) -> None:
    """Test getting French translations."""
    language.current_language = "fr"
    assert language.get_text("game_controls") == "Contrôles du Jeu"
    assert language.get_text("move_left_right") == "Déplacer gauche/droite"
    assert language.get_text("shoot") == "Tirer"
    assert language.get_text("pause_game") == "Pause"
    assert language.get_text("quit_game") == "Quitter"
    assert language.get_text("press_space") == "Appuyez sur ESPACE pour continuer"
    assert language.get_text("play") == "Jouer"
    assert language.get_text("score") == "Score"
    assert language.get_text("high_score") == "Meilleur Score"
    assert language.get_text("level") == "Niveau"
    assert language.get_text("ships") == "Vaisseaux"
    assert language.get_text("game_over") == "Partie Terminée"
    assert language.get_text("press_p") == "Appuyez sur 'P' pour reprendre"
    assert language.get_text("press_q") == "Appuyez sur 'Q' pour quitter"
    assert language.get_text("toggle_music") == "Musique on/off"
    assert language.get_text("toggle_sound") == "Son on/off"
    assert language.get_text("paused_game") == "Jeu en Pause"


def test_get_text_german(language: Language) -> None:
    """Test getting German translations."""
    language.current_language = "de"
    assert language.get_text("game_controls") == "Spielsteuerung"
    assert language.get_text("move_left_right") == "Links/Rechts bewegen"
    assert language.get_text("shoot") == "Schießen"
    assert language.get_text("pause_game") == "Spiel pausieren"
    assert language.get_text("quit_game") == "Spiel beenden"
    assert language.get_text("press_space") == "Drücke LEERTASTE zum Fortfahren"
    assert language.get_text("play") == "Spielen"
    assert language.get_text("score") == "Punktestand"
    assert language.get_text("high_score") == "Höchstpunktestand"
    assert language.get_text("level") == "Level"
    assert language.get_text("ships") == "Raumschiffe"
    assert language.get_text("game_over") == "Spiel Vorbei"
    assert language.get_text("press_p") == "Drücke 'P' zum Fortsetzen"
    assert language.get_text("press_q") == "Drücke 'Q' zum Beenden"
    assert language.get_text("toggle_music") == "Musik ein/aus"
    assert language.get_text("toggle_sound") == "Sound ein/aus"
    assert language.get_text("paused_game") == "Spiel Pausiert"


def test_get_text_italian(language: Language) -> None:
    """Test getting Italian translations."""
    language.current_language = "it"
    assert language.get_text("game_controls") == "Controlli di Gioco"
    assert language.get_text("move_left_right") == "Muovi sinistra/destra"
    assert language.get_text("shoot") == "Spara"
    assert language.get_text("pause_game") == "Pausa gioco"
    assert language.get_text("quit_game") == "Esci dal gioco"
    assert language.get_text("press_space") == "Premi SPAZIO per continuare"
    assert language.get_text("play") == "Gioca"
    assert language.get_text("score") == "Punteggio"
    assert language.get_text("high_score") == "Punteggio Massimo"
    assert language.get_text("level") == "Livello"
    assert language.get_text("ships") == "Navicelle"
    assert language.get_text("game_over") == "Gioco Finito"
    assert language.get_text("press_p") == "Premi 'P' per riprendere"
    assert language.get_text("press_q") == "Premi 'Q' per uscire"
    assert language.get_text("toggle_music") == "Musica on/off"
    assert language.get_text("toggle_sound") == "Suono on/off"
    assert language.get_text("paused_game") == "Gioco in Pausa"


def test_get_text_portuguese(language: Language) -> None:
    """Test getting Portuguese translations."""
    language.current_language = "pt"
    assert language.get_text("game_controls") == "Controles do Jogo"
    assert language.get_text("move_left_right") == "Mover esquerda/direita"
    assert language.get_text("shoot") == "Atirar"
    assert language.get_text("pause_game") == "Pausar jogo"
    assert language.get_text("quit_game") == "Sair do jogo"
    assert language.get_text("press_space") == "Pressione ESPAÇO para continuar"
    assert language.get_text("play") == "Jogar"
    assert language.get_text("score") == "Pontuação"
    assert language.get_text("high_score") == "Pontuação Máxima"
    assert language.get_text("level") == "Nível"
    assert language.get_text("ships") == "Naves"
    assert language.get_text("game_over") == "Jogo Terminado"
    assert language.get_text("press_p") == "Pressione 'P' para retomar"
    assert language.get_text("press_q") == "Pressione 'Q' para sair"
    assert language.get_text("toggle_music") == "Música on/off"
    assert language.get_text("toggle_sound") == "Som on/off"
    assert language.get_text("paused_game") == "Jogo em Pausa"


def test_get_text_arabic(language: Language) -> None:
    """Test getting Portuguese translations."""
    language.current_language = "ar"
    assert language.get_text("game_controls") == "عناصر التحكم في اللعبة"
    assert language.get_text("move_left_right") == "تحرك يسارًا/يمينًا"
    assert language.get_text("shoot") == "أطلق النار"
    assert language.get_text("pause_game") == "إيقاف اللعبة مؤقتًا"
    assert language.get_text("quit_game") == "إنهاء اللعبة"
    assert language.get_text("press_space") == "اضغط على SPACE للمتابعة"
    assert language.get_text("play") == "لعب"
    assert language.get_text("score") == "النتيجة"
    assert language.get_text("high_score") == "أعلى نتيجة"
    assert language.get_text("level") == "المستوى"
    assert language.get_text("ships") == "السفن"
    assert language.get_text("game_over") == "انتهت اللعبة"
    assert language.get_text("press_p") == "اضغط على 'P' للاستئناف"
    assert language.get_text("press_q") == "اضغط على 'Q' للخروج"
    assert language.get_text("toggle_music") == "تبديل الموسيقى"
    assert language.get_text("toggle_sound") == "تبديل الصوت"
    assert language.get_text("paused_game") == "اللعبة متوقفة مؤقتا"


def test_get_text_bulgarian(language: Language) -> None:
    """Test getting Bulgarian translations."""
    language.current_language = "bg"
    assert language.get_text("game_controls") == "Контроли на играта"
    assert language.get_text("move_left_right") == "Движение наляво/надясно"
    assert language.get_text("shoot") == "Стреляй"
    assert language.get_text("pause_game") == "Пауза на играта"
    assert language.get_text("quit_game") == "Изход от играта"
    assert language.get_text("press_space") == "Натиснете ПРОБЕЛ за продължаване"
    assert language.get_text("play") == "Играй"
    assert language.get_text("score") == "Точки"
    assert language.get_text("high_score") == "Рекордни точки"
    assert language.get_text("level") == "Ниво"
    assert language.get_text("ships") == "Кораби"
    assert language.get_text("game_over") == "Край на играта"
    assert language.get_text("press_p") == "Натиснете 'P' за възобновяване"
    assert language.get_text("press_q") == "Натиснете 'Q' за изход"
    assert language.get_text("toggle_music") == "Музика вкл./изкл."
    assert language.get_text("toggle_sound") == "Звук вкл./изкл."
    assert language.get_text("paused_game") == "Играта е паузирана"


def test_get_text_bengali(language: Language) -> None:
    """Test getting Bengali translations."""
    language.current_language = "bn"
    assert language.get_text("game_controls") == "গেম নিয়ন্ত্রণ"
    assert language.get_text("move_left_right") == "বাম/ডান সরান"
    assert language.get_text("shoot") == "গুলি চালান"
    assert language.get_text("pause_game") == "গেম বিরতি"
    assert language.get_text("quit_game") == "গেম ছেড়ে দিন"
    assert language.get_text("press_space") == "চালিয়ে যেতে স্পেস টিপুন"
    assert language.get_text("play") == "খেলুন"
    assert language.get_text("score") == "স্কোর"
    assert language.get_text("high_score") == "সর্বোচ্চ স্কোর"
    assert language.get_text("level") == "স্তর"
    assert language.get_text("ships") == "জাহাজ"
    assert language.get_text("game_over") == "গেম শেষ"
    assert language.get_text("press_p") == "পুনরায় চালু করতে 'P' টিপুন"
    assert language.get_text("press_q") == "ছেড়ে যেতে 'Q' টিপুন"
    assert language.get_text("toggle_music") == "সঙ্গীত চালু/বন্ধ"
    assert language.get_text("toggle_sound") == "শব্দ চালু/বন্ধ"
    assert language.get_text("paused_game") == "গেম বিরতিতে"


def test_get_text_catalan(language: Language) -> None:
    """Test getting Catalan translations."""
    language.current_language = "ca"
    assert language.get_text("game_controls") == "Controls del Joc"
    assert language.get_text("move_left_right") == "Moure esquerra/dreta"
    assert language.get_text("shoot") == "Disparar"
    assert language.get_text("pause_game") == "Pausar joc"
    assert language.get_text("quit_game") == "Sortir del joc"
    assert language.get_text("press_space") == "Premeu ESPAI per continuar"
    assert language.get_text("play") == "Jugar"
    assert language.get_text("score") == "Puntuació"
    assert language.get_text("high_score") == "Puntuació Màxima"
    assert language.get_text("level") == "Nivell"
    assert language.get_text("ships") == "Naus"
    assert language.get_text("game_over") == "Joc Acabat"
    assert language.get_text("press_p") == "Premeu 'P' per reprendre"
    assert language.get_text("press_q") == "Premeu 'Q' per sortir"
    assert language.get_text("toggle_music") == "Música on/off"
    assert language.get_text("toggle_sound") == "So on/off"
    assert language.get_text("paused_game") == "Joc en Pausa"


def test_get_text_czech(language: Language) -> None:
    """Test getting Czech translations."""
    language.current_language = "cs"
    assert language.get_text("game_controls") == "Ovládání Hry"
    assert language.get_text("move_left_right") == "Pohyb doleva/doprava"
    assert language.get_text("shoot") == "Střelba"
    assert language.get_text("pause_game") == "Pozastavit hru"
    assert language.get_text("quit_game") == "Ukončit hru"
    assert language.get_text("press_space") == "Stiskněte MEZERNÍK pro pokračování"
    assert language.get_text("play") == "Hrát"
    assert language.get_text("score") == "Skóre"
    assert language.get_text("high_score") == "Nejvyšší Skóre"
    assert language.get_text("level") == "Úroveň"
    assert language.get_text("ships") == "Lodě"
    assert language.get_text("game_over") == "Konec Hry"
    assert language.get_text("press_p") == "Stiskněte 'P' pro pokračování"
    assert language.get_text("press_q") == "Stiskněte 'Q' pro ukončení"
    assert language.get_text("toggle_music") == "Hudba zap/vyp"
    assert language.get_text("toggle_sound") == "Zvuk zap/vyp"
    assert language.get_text("paused_game") == "Hra Pozastavena"


def test_get_text_danish(language: Language) -> None:
    """Test getting Danish translations."""
    language.current_language = "da"
    assert language.get_text("game_controls") == "Spilkontroller"
    assert language.get_text("move_left_right") == "Bevæg venstre/højre"
    assert language.get_text("shoot") == "Skyd"
    assert language.get_text("pause_game") == "Pause spil"
    assert language.get_text("quit_game") == "Afslut spil"
    assert language.get_text("press_space") == "Tryk MELLEMRUM for at fortsætte"
    assert language.get_text("play") == "Spil"
    assert language.get_text("score") == "Score"
    assert language.get_text("high_score") == "Højeste Score"
    assert language.get_text("level") == "Niveau"
    assert language.get_text("ships") == "Skibe"
    assert language.get_text("game_over") == "Spil Slut"
    assert language.get_text("press_p") == "Tryk 'P' for at genoptage"
    assert language.get_text("press_q") == "Tryk 'Q' for at afslutte"
    assert language.get_text("toggle_music") == "Musik til/fra"
    assert language.get_text("toggle_sound") == "Lyd til/fra"
    assert language.get_text("paused_game") == "Spil Sat på Pause"


def test_get_text_greek(language: Language) -> None:
    """Test getting Greek translations."""
    language.current_language = "el"
    assert language.get_text("game_controls") == "Χειριστήρια Παιχνιδιού"
    assert language.get_text("move_left_right") == "Κίνηση αριστερά/δεξιά"
    assert language.get_text("shoot") == "Πυροβολισμός"
    assert language.get_text("pause_game") == "Παύση παιχνιδιού"
    assert language.get_text("quit_game") == "Έξοδος από το παιχνίδι"
    assert language.get_text("press_space") == "Πατήστε ΔΙΑΣΤΗΜΑ για συνέχεια"
    assert language.get_text("play") == "Παίξτε"
    assert language.get_text("score") == "Σκορ"
    assert language.get_text("high_score") == "Υψηλότερο Σκορ"
    assert language.get_text("level") == "Επίπεδο"
    assert language.get_text("ships") == "Πλοία"
    assert language.get_text("game_over") == "Τέλος Παιχνιδιού"
    assert language.get_text("press_p") == "Πατήστε 'P' για συνέχεια"
    assert language.get_text("press_q") == "Πατήστε 'Q' για έξοδο"
    assert language.get_text("toggle_music") == "Μουσική on/off"
    assert language.get_text("toggle_sound") == "Ήχος on/off"
    assert language.get_text("paused_game") == "Παιχνίδι σε Παύση"


def test_get_text_basque(language: Language) -> None:
    """Test getting Basque translations."""
    language.current_language = "eu"
    assert language.get_text("game_controls") == "Joko Kontrolak"
    assert language.get_text("move_left_right") == "Mugitu ezkerrera/eskuinera"
    assert language.get_text("shoot") == "Tiro egin"
    assert language.get_text("pause_game") == "Pausatu jokoa"
    assert language.get_text("quit_game") == "Jokotik irten"
    assert language.get_text("press_space") == "Sakatu ZURIUNEA jarraitzeko"
    assert language.get_text("play") == "Jokatu"
    assert language.get_text("score") == "Puntuazioa"
    assert language.get_text("high_score") == "Puntuazio Maximoa"
    assert language.get_text("level") == "Maila"
    assert language.get_text("ships") == "Ontziak"
    assert language.get_text("game_over") == "Joko Bukatua"
    assert language.get_text("press_p") == "Sakatu 'P' berriz hasteko"
    assert language.get_text("press_q") == "Sakatu 'Q' irteteko"
    assert language.get_text("toggle_music") == "Musika on/off"
    assert language.get_text("toggle_sound") == "Soinua on/off"
    assert language.get_text("paused_game") == "Jokoa Pausatuta"


def test_get_text_persian(language: Language) -> None:
    """Test getting Persian translations."""
    language.current_language = "fa"
    assert language.get_text("game_controls") == "کنترل‌های بازی"
    assert language.get_text("move_left_right") == "حرکت به چپ/راست"
    assert language.get_text("shoot") == "شلیک"
    assert language.get_text("pause_game") == "توقف بازی"
    assert language.get_text("quit_game") == "خروج از بازی"
    assert language.get_text("press_space") == "برای ادامه SPACE را فشار دهید"
    assert language.get_text("play") == "بازی"
    assert language.get_text("score") == "امتیاز"
    assert language.get_text("high_score") == "بالاترین امتیاز"
    assert language.get_text("level") == "سطح"
    assert language.get_text("ships") == "سفینه‌ها"
    assert language.get_text("game_over") == "بازی تمام شد"
    assert language.get_text("press_p") == "برای ادامه 'P' را فشار دهید"
    assert language.get_text("press_q") == "برای خروج 'Q' را فشار دهید"
    assert language.get_text("toggle_music") == "موسیقی روشن/خاموش"
    assert language.get_text("toggle_sound") == "صدا روشن/خاموش"
    assert language.get_text("paused_game") == "بازی متوقف شد"


def test_get_text_finnish(language: Language) -> None:
    """Test getting Finnish translations."""
    language.current_language = "fi"
    assert language.get_text("game_controls") == "Pelin Ohjaus"
    assert language.get_text("move_left_right") == "Liiku vasemmalle/oikealle"
    assert language.get_text("shoot") == "Ammu"
    assert language.get_text("pause_game") == "Keskeytä peli"
    assert language.get_text("quit_game") == "Poistu pelistä"
    assert language.get_text("press_space") == "Paina VÄLILYÖNTIÄ jatkaaksesi"
    assert language.get_text("play") == "Pelaa"
    assert language.get_text("score") == "Pisteet"
    assert language.get_text("high_score") == "Paras Tulos"
    assert language.get_text("level") == "Taso"
    assert language.get_text("ships") == "Alukset"
    assert language.get_text("game_over") == "Peli Päättyi"
    assert language.get_text("press_p") == "Paina 'P' jatkaaksesi"
    assert language.get_text("press_q") == "Paina 'Q' poistuaksesi"
    assert language.get_text("toggle_music") == "Musiikki päälle/pois"
    assert language.get_text("toggle_sound") == "Ääni päälle/pois"
    assert language.get_text("paused_game") == "Peli Keskeytetty"


def test_get_text_galician(language: Language) -> None:
    """Test getting Galician translations."""
    language.current_language = "gl"
    assert language.get_text("game_controls") == "Controis do Xogo"
    assert language.get_text("move_left_right") == "Mover esquerda/dereita"
    assert language.get_text("shoot") == "Disparar"
    assert language.get_text("pause_game") == "Pausar xogo"
    assert language.get_text("quit_game") == "Saír do xogo"
    assert language.get_text("press_space") == "Prema ESPAZO para continuar"
    assert language.get_text("play") == "Xogar"
    assert language.get_text("score") == "Puntuación"
    assert language.get_text("high_score") == "Puntuación Máxima"
    assert language.get_text("level") == "Nivel"
    assert language.get_text("ships") == "Naves"
    assert language.get_text("game_over") == "Xogo Rematado"
    assert language.get_text("press_p") == "Prema 'P' para retomar"
    assert language.get_text("press_q") == "Prema 'Q' para saír"
    assert language.get_text("toggle_music") == "Música on/off"
    assert language.get_text("toggle_sound") == "Son on/off"
    assert language.get_text("paused_game") == "Xogo en Pausa"


def test_get_text_hebrew(language: Language) -> None:
    """Test getting Hebrew translations."""
    language.current_language = "he"
    assert language.get_text("game_controls") == "בקרות משחק"
    assert language.get_text("move_left_right") == "זוז שמאלה/ימינה"
    assert language.get_text("shoot") == "ירי"
    assert language.get_text("pause_game") == "השהה משחק"
    assert language.get_text("quit_game") == "צא מהמשחק"
    assert language.get_text("press_space") == "לחץ על רווח להמשך"
    assert language.get_text("play") == "שחק"
    assert language.get_text("score") == "ניקוד"
    assert language.get_text("high_score") == "שיא"
    assert language.get_text("level") == "שלב"
    assert language.get_text("ships") == "ספינות"
    assert language.get_text("game_over") == "המשחק נגמר"
    assert language.get_text("press_p") == "לחץ על 'P' להמשיך"
    assert language.get_text("press_q") == "לחץ על 'Q' לצאת"
    assert language.get_text("toggle_music") == "מוזיקה דלוק/כבוי"
    assert language.get_text("toggle_sound") == "צליל דלוק/כבוי"
    assert language.get_text("paused_game") == "משחק מושהה"


def test_get_text_hindi(language: Language) -> None:
    """Test getting Hindi translations."""
    language.current_language = "hi"
    assert language.get_text("game_controls") == "गेम नियंत्रण"
    assert language.get_text("move_left_right") == "बाएं/दाएं घूमें"
    assert language.get_text("shoot") == "गोली चलाएं"
    assert language.get_text("pause_game") == "गेम रोकें"
    assert language.get_text("quit_game") == "गेम बंद करें"
    assert language.get_text("press_space") == "जारी रखने के लिए स्पेस दबाएं"
    assert language.get_text("play") == "खेलें"
    assert language.get_text("score") == "स्कोर"
    assert language.get_text("high_score") == "उच्च स्कोर"
    assert language.get_text("level") == "स्तर"
    assert language.get_text("ships") == "जहाज"
    assert language.get_text("game_over") == "गेम समाप्त"
    assert language.get_text("press_p") == "फिर से शुरू करने के लिए 'P' दबाएं"
    assert language.get_text("press_q") == "बाहर निकलने के लिए 'Q' दबाएं"
    assert language.get_text("toggle_music") == "संगीत चालू/बंद"
    assert language.get_text("toggle_sound") == "ध्वनि चालू/बंद"
    assert language.get_text("paused_game") == "गेम रोका गया"


def test_get_text_croatian(language: Language) -> None:
    """Test getting Croatian translations."""
    language.current_language = "hr"
    assert language.get_text("game_controls") == "Kontrole Igre"
    assert language.get_text("move_left_right") == "Pomakni lijevo/desno"
    assert language.get_text("shoot") == "Pucaj"
    assert language.get_text("pause_game") == "Pauziraj igru"
    assert language.get_text("quit_game") == "Izađi iz igre"
    assert language.get_text("press_space") == "Pritisni RAZMAK za nastavak"
    assert language.get_text("play") == "Igraj"
    assert language.get_text("score") == "Rezultat"
    assert language.get_text("high_score") == "Najbolji Rezultat"
    assert language.get_text("level") == "Razina"
    assert language.get_text("ships") == "Brodovi"
    assert language.get_text("game_over") == "Igra Završena"
    assert language.get_text("press_p") == "Pritisni 'P' za nastavak"
    assert language.get_text("press_q") == "Pritisni 'Q' za izlaz"
    assert language.get_text("toggle_music") == "Glazba uključeno/isključeno"
    assert language.get_text("toggle_sound") == "Zvuk uključeno/isključeno"
    assert language.get_text("paused_game") == "Igra Pauzirana"


def test_get_text_hungarian(language: Language) -> None:
    """Test getting Hungarian translations."""
    language.current_language = "hu"
    assert language.get_text("game_controls") == "Játék Vezérlők"
    assert language.get_text("move_left_right") == "Mozgás balra/jobbra"
    assert language.get_text("shoot") == "Lövés"
    assert language.get_text("pause_game") == "Játék szüneteltetése"
    assert language.get_text("quit_game") == "Kilépés a játékból"
    assert language.get_text("press_space") == "Nyomja meg a SZÓKÖZ billentyűt a folytatáshoz"
    assert language.get_text("play") == "Játék"
    assert language.get_text("score") == "Pontszám"
    assert language.get_text("high_score") == "Legjobb Pontszám"
    assert language.get_text("level") == "Szint"
    assert language.get_text("ships") == "Hajók"
    assert language.get_text("game_over") == "Játék Vége"
    assert language.get_text("press_p") == "Nyomja meg a 'P' billentyűt a folytatáshoz"
    assert language.get_text("press_q") == "Nyomja meg a 'Q' billentyűt a kilépéshez"
    assert language.get_text("toggle_music") == "Zene be/ki"
    assert language.get_text("toggle_sound") == "Hang be/ki"
    assert language.get_text("paused_game") == "Játék Szüneteltetve"


def test_get_text_indonesian(language: Language) -> None:
    """Test getting Indonesian translations."""
    language.current_language = "id"
    assert language.get_text("game_controls") == "Kontrol Permainan"
    assert language.get_text("move_left_right") == "Gerak kiri/kanan"
    assert language.get_text("shoot") == "Tembak"
    assert language.get_text("pause_game") == "Jeda permainan"
    assert language.get_text("quit_game") == "Keluar dari permainan"
    assert language.get_text("press_space") == "Tekan SPASI untuk melanjutkan"
    assert language.get_text("play") == "Main"
    assert language.get_text("score") == "Skor"
    assert language.get_text("high_score") == "Skor Tertinggi"
    assert language.get_text("level") == "Level"
    assert language.get_text("ships") == "Kapal"
    assert language.get_text("game_over") == "Permainan Selesai"
    assert language.get_text("press_p") == "Tekan 'P' untuk melanjutkan"
    assert language.get_text("press_q") == "Tekan 'Q' untuk keluar"
    assert language.get_text("toggle_music") == "Musik nyala/mati"
    assert language.get_text("toggle_sound") == "Suara nyala/mati"
    assert language.get_text("paused_game") == "Permainan Dijeda"


def test_get_text_japanese(language: Language) -> None:
    """Test getting Japanese translations."""
    language.current_language = "ja"
    assert language.get_text("game_controls") == "ゲームコントロール"
    assert language.get_text("move_left_right") == "左右に移動"
    assert language.get_text("shoot") == "射撃"
    assert language.get_text("pause_game") == "ゲームを一時停止"
    assert language.get_text("quit_game") == "ゲームを終了"
    assert language.get_text("press_space") == "続けるにはスペースキーを押してください"
    assert language.get_text("play") == "プレイ"
    assert language.get_text("score") == "スコア"
    assert language.get_text("high_score") == "ハイスコア"
    assert language.get_text("level") == "レベル"
    assert language.get_text("ships") == "船"
    assert language.get_text("game_over") == "ゲームオーバー"
    assert language.get_text("press_p") == "再開するには'P'を押してください"
    assert language.get_text("press_q") == "終了するには'Q'を押してください"
    assert language.get_text("toggle_music") == "音楽オン/オフ"
    assert language.get_text("toggle_sound") == "サウンドオン/オフ"
    assert language.get_text("paused_game") == "ゲーム一時停止中"


def test_get_text_kannada(language: Language) -> None:
    """Test getting Kannada translations."""
    language.current_language = "kn"
    assert language.get_text("game_controls") == "ಆಟದ ನಿಯಂತ್ರಣಗಳು"
    assert language.get_text("move_left_right") == "ಎಡ/ಬಲ ಚಲಿಸಿ"
    assert language.get_text("shoot") == "ಗುಂಡು ಹಾರಿಸಿ"
    assert language.get_text("pause_game") == "ಆಟವನ್ನು ವಿರಾಮಗೊಳಿಸಿ"
    assert language.get_text("quit_game") == "ಆಟದಿಂದ ನಿರ್ಗಮಿಸಿ"
    assert language.get_text("press_space") == "ಮುಂದುವರೆಯಲು ಸ್ಪೇಸ್ ಒತ್ತಿರಿ"
    assert language.get_text("play") == "ಆಡಿ"
    assert language.get_text("score") == "ಸ್ಕೋರ್"
    assert language.get_text("high_score") == "ಅತ್ಯುತ್ತಮ ಸ್ಕೋರ್"
    assert language.get_text("level") == "ಹಂತ"
    assert language.get_text("ships") == "ಹಡಗುಗಳು"
    assert language.get_text("game_over") == "ಆಟ ಮುಗಿದಿದೆ"
    assert language.get_text("press_p") == "ಪುನರಾರಂಭಿಸಲು 'P' ಒತ್ತಿರಿ"
    assert language.get_text("press_q") == "ನಿರ್ಗಮಿಸಲು 'Q' ಒತ್ತಿರಿ"
    assert language.get_text("toggle_music") == "ಸಂಗೀತ ಆನ್/ಆಫ್"
    assert language.get_text("toggle_sound") == "ಧ್ವನಿ ಆನ್/ಆಫ್"
    assert language.get_text("paused_game") == "ಆಟ ವಿರಾಮಗೊಳಿಸಲಾಗಿದೆ"


def test_get_text_korean(language: Language) -> None:
    """Test getting Korean translations."""
    language.current_language = "ko"
    assert language.get_text("game_controls") == "게임 조작"
    assert language.get_text("move_left_right") == "좌우 이동"
    assert language.get_text("shoot") == "발사"
    assert language.get_text("pause_game") == "게임 일시정지"
    assert language.get_text("quit_game") == "게임 종료"
    assert language.get_text("press_space") == "계속하려면 스페이스를 누르세요"
    assert language.get_text("play") == "플레이"
    assert language.get_text("score") == "점수"
    assert language.get_text("high_score") == "최고 점수"
    assert language.get_text("level") == "레벨"
    assert language.get_text("ships") == "우주선"
    assert language.get_text("game_over") == "게임 오버"
    assert language.get_text("press_p") == "재개하려면 'P'를 누르세요"
    assert language.get_text("press_q") == "종료하려면 'Q'를 누르세요"
    assert language.get_text("toggle_music") == "음악 켜기/끄기"
    assert language.get_text("toggle_sound") == "사운드 켜기/끄기"
    assert language.get_text("paused_game") == "게임 일시정지됨"


def test_get_text_malayalam(language: Language) -> None:
    """Test getting Malayalam translations."""
    language.current_language = "ml"
    assert language.get_text("game_controls") == "ഗെയിം നിയന്ത്രണങ്ങൾ"
    assert language.get_text("move_left_right") == "ഇടത്തോട്ട്/വലത്തോട്ട് നീങ്ങുക"
    assert language.get_text("shoot") == "വെടിവയ്ക്കുക"
    assert language.get_text("pause_game") == "ഗെയിം താൽക്കാലികമായി നിർത്തുക"
    assert language.get_text("quit_game") == "ഗെയിമിൽ നിന്ന് പുറത്തുകടക്കുക"
    assert language.get_text("press_space") == "തുടരാൻ സ്പേസ് അമർത്തുക"
    assert language.get_text("play") == "കളിക്കുക"
    assert language.get_text("score") == "സ്കോർ"
    assert language.get_text("high_score") == "ഉയർന്ന സ്കോർ"
    assert language.get_text("level") == "ലെവൽ"
    assert language.get_text("ships") == "കപ്പലുകൾ"
    assert language.get_text("game_over") == "ഗെയിം അവസാനിച്ചു"
    assert language.get_text("press_p") == "പുനരാരംഭിക്കാൻ 'P' അമർത്തുക"
    assert language.get_text("press_q") == "പുറത്തുകടക്കാൻ 'Q' അമർത്തുക"
    assert language.get_text("toggle_music") == "സംഗീതം ഓൺ/ഓഫ്"
    assert language.get_text("toggle_sound") == "ശബ്ദം ഓൺ/ഓഫ്"
    assert language.get_text("paused_game") == "ഗെയിം താൽക്കാലികമായി നിർത്തി"


def test_get_text_malay(language: Language) -> None:
    """Test getting Malay translations."""
    language.current_language = "ms"
    assert language.get_text("game_controls") == "Kawalan Permainan"
    assert language.get_text("move_left_right") == "Bergerak kiri/kanan"
    assert language.get_text("shoot") == "Tembak"
    assert language.get_text("pause_game") == "Jeda permainan"
    assert language.get_text("quit_game") == "Keluar dari permainan"
    assert language.get_text("press_space") == "Tekan RUANG untuk meneruskan"
    assert language.get_text("play") == "Main"
    assert language.get_text("score") == "Skor"
    assert language.get_text("high_score") == "Skor Tertinggi"
    assert language.get_text("level") == "Tahap"
    assert language.get_text("ships") == "Kapal"
    assert language.get_text("game_over") == "Permainan Tamat"
    assert language.get_text("press_p") == "Tekan 'P' untuk meneruskan"
    assert language.get_text("press_q") == "Tekan 'Q' untuk keluar"
    assert language.get_text("toggle_music") == "Muzik hidup/mati"
    assert language.get_text("toggle_sound") == "Bunyi hidup/mati"
    assert language.get_text("paused_game") == "Permainan Dijeda"


def test_get_text_dutch(language: Language) -> None:
    """Test getting Dutch translations."""
    language.current_language = "nl"
    assert language.get_text("game_controls") == "Spelbesturing"
    assert language.get_text("move_left_right") == "Beweeg links/rechts"
    assert language.get_text("shoot") == "Schieten"
    assert language.get_text("pause_game") == "Spel pauzeren"
    assert language.get_text("quit_game") == "Spel afsluiten"
    assert language.get_text("press_space") == "Druk op SPATIE om door te gaan"
    assert language.get_text("play") == "Spelen"
    assert language.get_text("score") == "Score"
    assert language.get_text("high_score") == "Hoogste Score"
    assert language.get_text("level") == "Level"
    assert language.get_text("ships") == "Schepen"
    assert language.get_text("game_over") == "Spel Afgelopen"
    assert language.get_text("press_p") == "Druk op 'P' om te hervatten"
    assert language.get_text("press_q") == "Druk op 'Q' om af te sluiten"
    assert language.get_text("toggle_music") == "Muziek aan/uit"
    assert language.get_text("toggle_sound") == "Geluid aan/uit"
    assert language.get_text("paused_game") == "Spel Gepauzeerd"


def test_get_text_norwegian(language: Language) -> None:
    """Test getting Norwegian translations."""
    language.current_language = "no"
    assert language.get_text("game_controls") == "Spillkontroller"
    assert language.get_text("move_left_right") == "Beveg venstre/høyre"
    assert language.get_text("shoot") == "Skyt"
    assert language.get_text("pause_game") == "Pause spill"
    assert language.get_text("quit_game") == "Avslutt spill"
    assert language.get_text("press_space") == "Trykk MELLOMROM for å fortsette"
    assert language.get_text("play") == "Spill"
    assert language.get_text("score") == "Poengsum"
    assert language.get_text("high_score") == "Høyeste Poengsum"
    assert language.get_text("level") == "Nivå"
    assert language.get_text("ships") == "Skip"
    assert language.get_text("game_over") == "Spill Slutt"
    assert language.get_text("press_p") == "Trykk 'P' for å fortsette"
    assert language.get_text("press_q") == "Trykk 'Q' for å avslutte"
    assert language.get_text("toggle_music") == "Musikk på/av"
    assert language.get_text("toggle_sound") == "Lyd på/av"
    assert language.get_text("paused_game") == "Spill Pauset"


def test_get_text_polish(language: Language) -> None:
    """Test getting Polish translations."""
    language.current_language = "pl"
    assert language.get_text("game_controls") == "Sterowanie Grą"
    assert language.get_text("move_left_right") == "Ruch w lewo/prawo"
    assert language.get_text("shoot") == "Strzelaj"
    assert language.get_text("pause_game") == "Wstrzymaj grę"
    assert language.get_text("quit_game") == "Wyjdź z gry"
    assert language.get_text("press_space") == "Naciśnij SPACJĘ, aby kontynuować"
    assert language.get_text("play") == "Graj"
    assert language.get_text("score") == "Wynik"
    assert language.get_text("high_score") == "Najlepszy Wynik"
    assert language.get_text("level") == "Poziom"
    assert language.get_text("ships") == "Statki"
    assert language.get_text("game_over") == "Koniec Gry"
    assert language.get_text("press_p") == "Naciśnij 'P', aby wznowić"
    assert language.get_text("press_q") == "Naciśnij 'Q', aby wyjść"
    assert language.get_text("toggle_music") == "Muzyka wł/wył"
    assert language.get_text("toggle_sound") == "Dźwięk wł/wył"
    assert language.get_text("paused_game") == "Gra Wstrzymana"


def test_get_text_romanian(language: Language) -> None:
    """Test getting Romanian translations."""
    language.current_language = "ro"
    assert language.get_text("game_controls") == "Controale Joc"
    assert language.get_text("move_left_right") == "Mișcare stânga/dreapta"
    assert language.get_text("shoot") == "Trage"
    assert language.get_text("pause_game") == "Pauză joc"
    assert language.get_text("quit_game") == "Ieși din joc"
    assert language.get_text("press_space") == "Apăsați SPAȚIU pentru a continua"
    assert language.get_text("play") == "Joacă"
    assert language.get_text("score") == "Scor"
    assert language.get_text("high_score") == "Cel Mai Mare Scor"
    assert language.get_text("level") == "Nivel"
    assert language.get_text("ships") == "Nave"
    assert language.get_text("game_over") == "Joc Terminat"
    assert language.get_text("press_p") == "Apăsați 'P' pentru a relua"
    assert language.get_text("press_q") == "Apăsați 'Q' pentru a ieși"
    assert language.get_text("toggle_music") == "Muzică pornit/oprit"
    assert language.get_text("toggle_sound") == "Sunet pornit/oprit"
    assert language.get_text("paused_game") == "Joc În Pauză"


def test_get_text_russian(language: Language) -> None:
    """Test getting Russian translations."""
    language.current_language = "ru"
    assert language.get_text("game_controls") == "Управление Игрой"
    assert language.get_text("move_left_right") == "Движение влево/вправо"
    assert language.get_text("shoot") == "Стрелять"
    assert language.get_text("pause_game") == "Пауза"
    assert language.get_text("quit_game") == "Выйти из игры"
    assert language.get_text("press_space") == "Нажмите ПРОБЕЛ для продолжения"
    assert language.get_text("play") == "Играть"
    assert language.get_text("score") == "Счёт"
    assert language.get_text("high_score") == "Рекордный Счёт"
    assert language.get_text("level") == "Уровень"
    assert language.get_text("ships") == "Корабли"
    assert language.get_text("game_over") == "Игра Окончена"
    assert language.get_text("press_p") == "Нажмите 'P' для продолжения"
    assert language.get_text("press_q") == "Нажмите 'Q' для выхода"
    assert language.get_text("toggle_music") == "Музыка вкл/выкл"
    assert language.get_text("toggle_sound") == "Звук вкл/выкл"
    assert language.get_text("paused_game") == "Игра На Паузе"


def test_get_text_slovak(language: Language) -> None:
    """Test getting Slovak translations."""
    language.current_language = "sk"
    assert language.get_text("game_controls") == "Ovládanie Hry"
    assert language.get_text("move_left_right") == "Pohyb doľava/doprava"
    assert language.get_text("shoot") == "Strieľať"
    assert language.get_text("pause_game") == "Pozastaviť hru"
    assert language.get_text("quit_game") == "Ukončiť hru"
    assert language.get_text("press_space") == "Stlačte MEDZERNÍK pre pokračovanie"
    assert language.get_text("play") == "Hrať"
    assert language.get_text("score") == "Skóre"
    assert language.get_text("high_score") == "Najvyššie Skóre"
    assert language.get_text("level") == "Úroveň"
    assert language.get_text("ships") == "Lode"
    assert language.get_text("game_over") == "Koniec Hry"
    assert language.get_text("press_p") == "Stlačte 'P' pre pokračovanie"
    assert language.get_text("press_q") == "Stlačte 'Q' pre ukončenie"
    assert language.get_text("toggle_music") == "Hudba zap/vyp"
    assert language.get_text("toggle_sound") == "Zvuk zap/vyp"
    assert language.get_text("paused_game") == "Hra Pozastavená"


def test_get_text_serbian(language: Language) -> None:
    """Test getting Serbian translations."""
    language.current_language = "sr"
    assert language.get_text("game_controls") == "Контроле Игре"
    assert language.get_text("move_left_right") == "Померање лево/десно"
    assert language.get_text("shoot") == "Пуцај"
    assert language.get_text("pause_game") == "Паузирај игру"
    assert language.get_text("quit_game") == "Изађи из игре"
    assert language.get_text("press_space") == "Притисни РАЗМАК за наставак"
    assert language.get_text("play") == "Играј"
    assert language.get_text("score") == "Резултат"
    assert language.get_text("high_score") == "Највећи Резултат"
    assert language.get_text("level") == "Ниво"
    assert language.get_text("ships") == "Бродови"
    assert language.get_text("game_over") == "Игра Завршена"
    assert language.get_text("press_p") == "Притисни 'P' за наставак"
    assert language.get_text("press_q") == "Притисни 'Q' за излаз"
    assert language.get_text("toggle_music") == "Музика укључено/искључено"
    assert language.get_text("toggle_sound") == "Звук укључено/искључено"
    assert language.get_text("paused_game") == "Игра Паузирана"


def test_get_text_swedish(language: Language) -> None:
    """Test getting Swedish translations."""
    language.current_language = "sv"
    assert language.get_text("game_controls") == "Spelkontroller"
    assert language.get_text("move_left_right") == "Flytta vänster/höger"
    assert language.get_text("shoot") == "Skjut"
    assert language.get_text("pause_game") == "Pausa spel"
    assert language.get_text("quit_game") == "Avsluta spel"
    assert language.get_text("press_space") == "Tryck MELLANSLAG för att fortsätta"
    assert language.get_text("play") == "Spela"
    assert language.get_text("score") == "Poäng"
    assert language.get_text("high_score") == "Högsta Poäng"
    assert language.get_text("level") == "Nivå"
    assert language.get_text("ships") == "Skepp"
    assert language.get_text("game_over") == "Spel Slut"
    assert language.get_text("press_p") == "Tryck 'P' för att återuppta"
    assert language.get_text("press_q") == "Tryck 'Q' för att avsluta"
    assert language.get_text("toggle_music") == "Musik på/av"
    assert language.get_text("toggle_sound") == "Ljud på/av"
    assert language.get_text("paused_game") == "Spel Pausat"


def test_get_text_swahili(language: Language) -> None:
    """Test getting Swahili translations."""
    language.current_language = "sw"
    assert language.get_text("game_controls") == "Udhibiti wa Mchezo"
    assert language.get_text("move_left_right") == "Sogea kushoto/kulia"
    assert language.get_text("shoot") == "Piga risasi"
    assert language.get_text("pause_game") == "Simamisha mchezo"
    assert language.get_text("quit_game") == "Toka kwenye mchezo"
    assert language.get_text("press_space") == "Bonyeza NAFASI kuendelea"
    assert language.get_text("play") == "Cheza"
    assert language.get_text("score") == "Alama"
    assert language.get_text("high_score") == "Alama ya Juu"
    assert language.get_text("level") == "Kiwango"
    assert language.get_text("ships") == "Meli"
    assert language.get_text("game_over") == "Mchezo Umekwisha"
    assert language.get_text("press_p") == "Bonyeza 'P' kuendelea"
    assert language.get_text("press_q") == "Bonyeza 'Q' kutoka"
    assert language.get_text("toggle_music") == "Muziki washa/zima"
    assert language.get_text("toggle_sound") == "Sauti washa/zima"
    assert language.get_text("paused_game") == "Mchezo Umesimamishwa"


def test_get_text_tamil(language: Language) -> None:
    """Test getting Tamil translations."""
    language.current_language = "ta"
    assert language.get_text("game_controls") == "விளையாட்டு கட்டுப்பாடுகள்"
    assert language.get_text("move_left_right") == "இடது/வலது நகர்த்தவும்"
    assert language.get_text("shoot") == "சுடவும்"
    assert language.get_text("pause_game") == "விளையாட்டை இடைநிறுத்தவும்"
    assert language.get_text("quit_game") == "விளையாட்டிலிருந்து வெளியேறவும்"
    assert language.get_text("press_space") == "தொடர SPACE ஐ அழுத்தவும்"
    assert language.get_text("play") == "விளையாடு"
    assert language.get_text("score") == "மதிப்பெண்"
    assert language.get_text("high_score") == "உயர் மதிப்பெண்"
    assert language.get_text("level") == "நிலை"
    assert language.get_text("ships") == "கப்பல்கள்"
    assert language.get_text("game_over") == "விளையாட்டு முடிந்தது"
    assert language.get_text("press_p") == "மீண்டும் தொடங்க 'P' ஐ அழுத்தவும்"
    assert language.get_text("press_q") == "வெளியேற 'Q' ஐ அழுத்தவும்"
    assert language.get_text("toggle_music") == "இசை ஆன்/ஆஃப்"
    assert language.get_text("toggle_sound") == "ஒலி ஆன்/ஆஃப்"
    assert language.get_text("paused_game") == "விளையாட்டு இடைநிறுத்தப்பட்டது"


def test_get_text_telugu(language: Language) -> None:
    """Test getting Telugu translations."""
    language.current_language = "te"
    assert language.get_text("game_controls") == "గేమ్ నియంత్రణలు"
    assert language.get_text("move_left_right") == "ఎడమ/కుడి కదలండి"
    assert language.get_text("shoot") == "కాల్చండి"
    assert language.get_text("pause_game") == "గేమ్‌ను పాజ్ చేయండి"
    assert language.get_text("quit_game") == "గేమ్ నుండి నిష్క్రమించండి"
    assert language.get_text("press_space") == "కొనసాగించడానికి స్పేస్ నొక్కండి"
    assert language.get_text("play") == "ఆడండి"
    assert language.get_text("score") == "స్కోర్"
    assert language.get_text("high_score") == "అత్యధిక స్కోర్"
    assert language.get_text("level") == "స్థాయి"
    assert language.get_text("ships") == "నౌకలు"
    assert language.get_text("game_over") == "గేమ్ ముగిసింది"
    assert language.get_text("press_p") == "పునఃప్రారంభించడానికి 'P' నొక్కండి"
    assert language.get_text("press_q") == "నిష్క్రమించడానికి 'Q' నొక్కండి"
    assert language.get_text("toggle_music") == "సంగీతం ఆన్/ఆఫ్"
    assert language.get_text("toggle_sound") == "ధ్వని ఆన్/ఆఫ్"
    assert language.get_text("paused_game") == "గేమ్ పాజ్ చేయబడింది"


def test_get_text_thai(language: Language) -> None:
    """Test getting Thai translations."""
    language.current_language = "th"
    assert language.get_text("game_controls") == "การควบคุมเกม"
    assert language.get_text("move_left_right") == "เคลื่อนที่ซ้าย/ขวา"
    assert language.get_text("shoot") == "ยิง"
    assert language.get_text("pause_game") == "หยุดเกมชั่วคราว"
    assert language.get_text("quit_game") == "ออกจากเกม"
    assert language.get_text("press_space") == "กด SPACE เพื่อดำเนินการต่อ"
    assert language.get_text("play") == "เล่น"
    assert language.get_text("score") == "คะแนน"
    assert language.get_text("high_score") == "คะแนนสูงสุด"
    assert language.get_text("level") == "ระดับ"
    assert language.get_text("ships") == "ยานอวกาศ"
    assert language.get_text("game_over") == "เกมจบ"
    assert language.get_text("press_p") == "กด 'P' เพื่อเล่นต่อ"
    assert language.get_text("press_q") == "กด 'Q' เพื่อออก"
    assert language.get_text("toggle_music") == "เปิด/ปิดเพลง"
    assert language.get_text("toggle_sound") == "เปิด/ปิดเสียง"
    assert language.get_text("paused_game") == "เกมหยุดชั่วคราว"


def test_get_text_tagalog(language: Language) -> None:
    """Test getting Tagalog translations."""
    language.current_language = "tl"
    assert language.get_text("game_controls") == "Mga Kontrol ng Laro"
    assert language.get_text("move_left_right") == "Gumalaw pakaliwa/pakanan"
    assert language.get_text("shoot") == "Bumaril"
    assert language.get_text("pause_game") == "I-pause ang laro"
    assert language.get_text("quit_game") == "Lumabas sa laro"
    assert language.get_text("press_space") == "Pindutin ang SPACE upang magpatuloy"
    assert language.get_text("play") == "Maglaro"
    assert language.get_text("score") == "Puntos"
    assert language.get_text("high_score") == "Pinakamataas na Puntos"
    assert language.get_text("level") == "Antas"
    assert language.get_text("ships") == "Mga Barko"
    assert language.get_text("game_over") == "Tapos na ang Laro"
    assert language.get_text("press_p") == "Pindutin ang 'P' upang magpatuloy"
    assert language.get_text("press_q") == "Pindutin ang 'Q' upang lumabas"
    assert language.get_text("toggle_music") == "Musika bukas/sara"
    assert language.get_text("toggle_sound") == "Tunog bukas/sara"
    assert language.get_text("paused_game") == "Naka-pause ang Laro"


def test_get_text_turkish(language: Language) -> None:
    """Test getting Turkish translations."""
    language.current_language = "tr"
    assert language.get_text("game_controls") == "Oyun Kontrolleri"
    assert language.get_text("move_left_right") == "Sola/sağa hareket"
    assert language.get_text("shoot") == "Ateş et"
    assert language.get_text("pause_game") == "Oyunu duraklat"
    assert language.get_text("quit_game") == "Oyundan çık"
    assert language.get_text("press_space") == "Devam etmek için BOŞLUK tuşuna basın"
    assert language.get_text("play") == "Oyna"
    assert language.get_text("score") == "Skor"
    assert language.get_text("high_score") == "En Yüksek Skor"
    assert language.get_text("level") == "Seviye"
    assert language.get_text("ships") == "Gemiler"
    assert language.get_text("game_over") == "Oyun Bitti"
    assert language.get_text("press_p") == "Devam etmek için 'P' tuşuna basın"
    assert language.get_text("press_q") == "Çıkmak için 'Q' tuşuna basın"
    assert language.get_text("toggle_music") == "Müzik açık/kapalı"
    assert language.get_text("toggle_sound") == "Ses açık/kapalı"
    assert language.get_text("paused_game") == "Oyun Duraklatıldı"


def test_get_text_ukrainian(language: Language) -> None:
    """Test getting Ukrainian translations."""
    language.current_language = "uk"
    assert language.get_text("game_controls") == "Керування Грою"
    assert language.get_text("move_left_right") == "Рух вліво/вправо"
    assert language.get_text("shoot") == "Стріляти"
    assert language.get_text("pause_game") == "Пауза"
    assert language.get_text("quit_game") == "Вийти з гри"
    assert language.get_text("press_space") == "Натисніть ПРОБІЛ для продовження"
    assert language.get_text("play") == "Грати"
    assert language.get_text("score") == "Рахунок"
    assert language.get_text("high_score") == "Найкращий Рахунок"
    assert language.get_text("level") == "Рівень"
    assert language.get_text("ships") == "Кораблі"
    assert language.get_text("game_over") == "Гра Закінчена"
    assert language.get_text("press_p") == "Натисніть 'P' для продовження"
    assert language.get_text("press_q") == "Натисніть 'Q' для виходу"
    assert language.get_text("toggle_music") == "Музика увімк/вимк"
    assert language.get_text("toggle_sound") == "Звук увімк/вимк"
    assert language.get_text("paused_game") == "Гра На Паузі"


def test_get_text_urdu(language: Language) -> None:
    """Test getting Urdu translations."""
    language.current_language = "ur"
    assert language.get_text("game_controls") == "گیم کنٹرولز"
    assert language.get_text("move_left_right") == "بائیں/دائیں جانب حرکت"
    assert language.get_text("shoot") == "فائر کریں"
    assert language.get_text("pause_game") == "گیم روکیں"
    assert language.get_text("quit_game") == "گیم سے باہر نکلیں"
    assert language.get_text("press_space") == "جاری رکھنے کے لیے SPACE دبائیں"
    assert language.get_text("play") == "کھیلیں"
    assert language.get_text("score") == "سکور"
    assert language.get_text("high_score") == "بلند ترین سکور"
    assert language.get_text("level") == "سطح"
    assert language.get_text("ships") == "جہاز"
    assert language.get_text("game_over") == "گیم ختم"
    assert language.get_text("press_p") == "دوبارہ شروع کرنے کے لیے 'P' دبائیں"
    assert language.get_text("press_q") == "باہر نکلنے کے لیے 'Q' دبائیں"
    assert language.get_text("toggle_music") == "موسیقی آن/آف"
    assert language.get_text("toggle_sound") == "آواز آن/آف"
    assert language.get_text("paused_game") == "گیم رک گئی"


def test_get_text_vietnamese(language: Language) -> None:
    """Test getting Vietnamese translations."""
    language.current_language = "vi"
    assert language.get_text("game_controls") == "Điều Khiển Trò Chơi"
    assert language.get_text("move_left_right") == "Di chuyển trái/phải"
    assert language.get_text("shoot") == "Bắn"
    assert language.get_text("pause_game") == "Tạm dừng trò chơi"
    assert language.get_text("quit_game") == "Thoát khỏi trò chơi"
    assert language.get_text("press_space") == "Nhấn SPACE để tiếp tục"
    assert language.get_text("play") == "Chơi"
    assert language.get_text("score") == "Điểm"
    assert language.get_text("high_score") == "Điểm Cao Nhất"
    assert language.get_text("level") == "Cấp độ"
    assert language.get_text("ships") == "Tàu"
    assert language.get_text("game_over") == "Trò Chơi Kết Thúc"
    assert language.get_text("press_p") == "Nhấn 'P' để tiếp tục"
    assert language.get_text("press_q") == "Nhấn 'Q' để thoát"
    assert language.get_text("toggle_music") == "Nhạc bật/tắt"
    assert language.get_text("toggle_sound") == "Âm thanh bật/tắt"
    assert language.get_text("paused_game") == "Trò Chơi Tạm Dừng"


def test_get_text_chinese_simplified(language: Language) -> None:
    """Test getting Chinese Simplified translations."""
    language.current_language = "zh"
    assert language.get_text("game_controls") == "游戏控制"
    assert language.get_text("move_left_right") == "向左/向右移动"
    assert language.get_text("shoot") == "射击"
    assert language.get_text("pause_game") == "暂停游戏"
    assert language.get_text("quit_game") == "退出游戏"
    assert language.get_text("press_space") == "按空格键继续"
    assert language.get_text("play") == "开始游戏"
    assert language.get_text("score") == "得分"
    assert language.get_text("high_score") == "最高分"
    assert language.get_text("level") == "关卡"
    assert language.get_text("ships") == "飞船"
    assert language.get_text("game_over") == "游戏结束"
    assert language.get_text("press_p") == "按'P'继续"
    assert language.get_text("press_q") == "按'Q'退出"
    assert language.get_text("toggle_music") == "音乐开/关"
    assert language.get_text("toggle_sound") == "音效开/关"
    assert language.get_text("paused_game") == "游戏已暂停"


def test_get_text_chinese_traditional(language: Language) -> None:
    """Test getting Chinese Traditional translations."""
    language.current_language = "zh-TW"
    assert language.get_text("game_controls") == "遊戲控制"
    assert language.get_text("move_left_right") == "向左/向右移動"
    assert language.get_text("shoot") == "射擊"
    assert language.get_text("pause_game") == "暫停遊戲"
    assert language.get_text("quit_game") == "退出遊戲"
    assert language.get_text("press_space") == "按空格鍵繼續"
    assert language.get_text("play") == "開始遊戲"
    assert language.get_text("score") == "得分"
    assert language.get_text("high_score") == "最高分"
    assert language.get_text("level") == "關卡"
    assert language.get_text("ships") == "飛船"
    assert language.get_text("game_over") == "遊戲結束"
    assert language.get_text("press_p") == "按'P'繼續"
    assert language.get_text("press_q") == "按'Q'退出"
    assert language.get_text("toggle_music") == "音樂開/關"
    assert language.get_text("toggle_sound") == "音效開/關"
    assert language.get_text("paused_game") == "遊戲已暫停"


def test_missing_translation_fallback(language: Language) -> None:
    """Test fallback to English for missing translations."""
    language.current_language = "es"
    # Test with a non-existent key
    assert language.get_text("non_existent_key") == "non_existent_key"


def test_system_language_detection(language: Language) -> None:
    """Test system language detection."""
    system_language = language._get_system_language()
    assert isinstance(system_language, str)
    assert len(system_language) == 2  # Language codes are 2 characters


def test_supported_language_selection(language: Language) -> None:
    """Test supported language selection."""
    for lang in Language.SUPPORTED_LANGUAGES:
        language.system_language = lang
        assert language._get_supported_language() == lang

    # Test with unsupported language (should default to English)
    language.system_language = "xx"  # Invalid language code
    assert language._get_supported_language() == Language.DEFAULT_LANGUAGE


def test_translation_file_loading(language: Language) -> None:
    """Test if translation files are loaded correctly."""
    # Check if all required keys are present in all languages
    required_keys: List[str] = [
        "game_controls",
        "move_left_right",
        "shoot",
        "pause_game",
        "quit_game",
        "press_space",
        "play",
        "score",
        "high_score",
        "level",
        "ships",
        "game_over",
        "press_p",
        "press_q",
        "paused_game",
    ]

    for lang in Language.SUPPORTED_LANGUAGES:
        for key in required_keys:
            assert key in language.translations[lang]
            assert isinstance(language.translations[lang][key], str)


def test_set_language(language: Language) -> None:
    """Test setting language."""
    # Test setting supported language
    assert language.set_language("es") is True
    assert language.current_language == "es"

    # Test setting unsupported language
    assert language.set_language("xx") is False  # Invalid language code
    assert language.current_language == "es"  # Should not change


def test_get_available_languages(language: Language) -> None:
    """Test getting available languages."""
    available_languages = language.get_available_languages()
    assert isinstance(available_languages, list)
    assert all(lang in Language.SUPPORTED_LANGUAGES for lang in available_languages)
    assert len(available_languages) == len(Language.SUPPORTED_LANGUAGES)
